--Creacion de tablas
DROP TABLE usuario;
CREATE TABLE USUARIO(
ID_USUARIO INTEGER NOT NULL,
NOMBRE VARCHAR(125),
APELLIDO VARCHAR(125),
NIT NUMBER(13),
FECHA_NACIMIENTO DATE,
CONSTRAINT pk_usuarios primary key(ID_USUARIO)
);

DROP TABLE EMPLEADO;
CREATE TABLE EMPLEADO(
ID_EMPLEADO INT NOT NULL,
ID_USUARIO INT,
ID_ROL INT,
CODIGO NUMBER(10),
CONSTRAINT PK_EMPLEADOS PRIMARY KEY(ID_EMPLEADO),
CONSTRAINT FK_EMPLEADOS_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES  USUARIO(ID_USUARIO),
CONSTRAINT FK_EMPLEADOS_ROLES FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)

);

DROP TABLE ROL;
CREATE TABLE ROL(
ID_ROL INT NOT NULL,
AREA VARCHAR(250),
ROL VARCHAR(250),
CONSTRAINT pk_rol primary key(ID_ROL)
);

DROP TABLE TELEFONO;
CREATE TABLE TELEFONO(
ID_TELEFONO INT NOT NULL,
TELEFONO NUMBER (11),
EXTENSION NUMBER(5),
ID_USUARIO INT,
CONSTRAINT PK_TELEFONO PRIMARY KEY(ID_TELEFONO),
CONSTRAINT FK_TELEFONO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

DROP TABLE CORREO;
CREATE TABLE CORREO(
ID_CORREO INT NOT NULL,
CORREO VARCHAR(250),
ID_USUARIO INT,
CONSTRAINT PK_CORREO PRIMARY KEY(ID_CORREO),
CONSTRAINT FK_CORREO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Restricciones
ALTER TABLE CORREO
    ADD CONSTRAINT TUSUARIO_UNIQUE UNIQUE (ID_USUARIO);
    
ALTER TABLE TELEFONO
    ADD CONSTRAINT CUSUARIO_UNIQUE UNIQUE (ID_USUARIO);
    
ALTER TABLE EMPLEADO
    ADD CONSTRAINT EUSUARIO_UNIQUE UNIQUE (ID_USUARIO);
    
ALTER TABLE EMPLEADO
    ADD CONSTRAINT EROL_UNIQUE UNIQUE (ID_ROL);
--Visualización
SELECT * FROM USUARIO;
SELECT * FROM EMPLEADO;
SELECT * FROM ROL;
SELECT * FROM TELEFONO;
SELECT * FROM CORREO;

--Insercion de datos